framework:
    #esi:             ~
    translator:      { fallback: en }
    serializer:      { enable_annotations: true }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enabled: true, api: auto, enable_annotations: true, strict_email: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true
    cache:
#       app: cache.adapter.apcu
        app: cache.adapter.filesystem
        system: cache.adapter.system
        directory: /var/www/partkeepr/app/cache
#       pools:
#              app.cache.api:
#              adapter : [cache.app]
        pools:
               app.cache.api:
               adapter : [cache.adapter.memcached]
               default_lifetime : 3600
 