services:
    csv_responder_view_listener:
        class: PartKeepr\ExportBundle\EventListener\CsvResponderViewListener
        tags:
            - { name: "kernel.event_listener", event: "kernel.view", method: "onKernelView" }

    xlsx_responder_view_listener:
        class: PartKeepr\ExportBundle\EventListener\XmlExcelResponderViewListener
        tags:
            - { name: "kernel.event_listener", event: "kernel.view", method: "onKernelView" }

    part_image_listener:
        class: PartKeepr\PartBundle\Listeners\ImageAttachmentListener
        arguments:
            - "@partkeepr_image_service"
        tags:
            - { name: doctrine.event_listener, event: postLoad }

    partkeepr_legacy_user_provider:
        class: PartKeepr\AuthBundle\Security\User\LegacyUserProvider
        arguments:
            - "@doctrine.orm.default_entity_manager"

    footprint.category_path_listener:
        class: PartKeepr\FootprintBundle\Listeners\CategoryPathListener
        arguments:
            - "@service_container"
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    storage_location.category_path_listener:
        class: PartKeepr\StorageLocationBundle\Listeners\CategoryPathListener
        arguments:
            - "@service_container"
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    part.category_path_listener:
        class: PartKeepr\PartBundle\Listeners\CategoryPathListener
        arguments:
            - "@service_container"
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    part.stock_level_listener:
        class: PartKeepr\PartBundle\Listeners\StockLevelListener
        arguments:
            - "@service_container"
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    footprint_category.root_category_listener:
        class: PartKeepr\CategoryBundle\EventListener\RootCategoryListener
        arguments:
            - "@service_container"
            - "partkeepr.footprint.category_service"
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    part_category.root_category_listener:
        class: PartKeepr\CategoryBundle\EventListener\RootCategoryListener
        arguments:
            - "@service_container"
            - "partkeepr.part.category_service"
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    storage_location_category.root_category_listener:
        class: PartKeepr\CategoryBundle\EventListener\RootCategoryListener
        arguments:
            - "@service_container"
            - "partkeepr.storage_location.category_service"
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    file_removal_listener:
        class:    PartKeepr\UploadedFileBundle\EventListener\FileRemovalListener
        arguments:
            - "@partkeepr_uploadedfile_service"
            - "@annotation_reader"
            - "@property_accessor"
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    temporary_file_listener:
        class:    PartKeepr\UploadedFileBundle\EventListener\TemporaryFileEventListener
        arguments:
            - "@partkeepr_uploadedfile_service"
            - "@partkeepr_image_service"
            - "@annotation_reader"
            - "@property_accessor"
            - "@api.iri_converter"
        tags:  [ { name: "kernel.event_listener", event: "kernel.view", method: "replaceTemporaryFile", priority: 100 } ]

    resource.system_notice.item_operation.get:
        class:     "Dunglas\\ApiBundle\\Api\\Operation\\Operation"
        public:    false
        factory:   [ "@api.operation_factory", "createItemOperation" ]
        arguments: [ "@resource.system_notice", "GET" ]

    resource.system_notice.item_operation.acknowledge:
        class:     "Dunglas\\ApiBundle\\Api\\Operation\\Operation"
        public:    false
        factory:   [ "@api.operation_factory", "createItemOperation" ]
        arguments:
             -    "@resource.system_notice"               # Resource
             -    [ "PUT" ]                 # Methods
             -    "/system_notices/{id}/acknowledge"           # Path
             -    "partkeepr.system_notice.acknowledge"         # Controller
             -    "SystemNoticeAcknowledge"                 # Route name


    resource.system_preference.item_operation.get_preferences:
        class:     "Dunglas\\ApiBundle\\Api\\Operation\\Operation"
        public:    false
        factory:   [ "@api.operation_factory", "createCollectionOperation" ]
        arguments:
             -    "@resource.system_preference"               # Resource
             -    [ "GET" ]                 # Methods
             -    "/system_preferences"           # Path
             -    "partkeepr.system_preference.get_preferences"         # Controller
             -    "PartKeeprSystemPreferenceGet"

    resource.system_preference.item_operation.set_preference:
        class:     "Dunglas\\ApiBundle\\Api\\Operation\\Operation"
        public:    false
        factory:   [ "@api.operation_factory", "createCollectionOperation" ]
        arguments:
             -    "@resource.system_preference"               # Resource
             -    [ "POST", "PUT" ]                 # Methods
             -    "/system_preferences"           # Path
             -    "partkeepr.system_preference.set_preference"         # Controller
             -    "PartKeeprSystemPreferenceSet"

    resource.system_preference.item_operation.delete_preference:
        class:     "Dunglas\\ApiBundle\\Api\\Operation\\Operation"
        public:    false
        factory:   [ "@api.operation_factory", "createItemOperation" ]
        arguments:
             -    "@resource.system_preference"               # Resource
             -    [ "DELETE" ]                 # Methods
             -    "/system_preferences"           # Path
             -    "partkeepr.system_preference.delete_preference"         # Controller
             -    "PartKeeprSystemPreferenceDelete"
