dunglas_api:
    title:       "PartKeepr"
    description: "The PartKeepr REST API"
    collection:
        order_parameter_name:          'order'
        order:                         'ASC'
        pagination:
            client_enabled:            true
            client_items_per_page:     true
#           items_per_page:            3
    supported_formats: [ "jsonld", "csv", "xlsx" ]
    cache: %cache.dunglas%
